// // This is the code generated by GenerateAst.java version 2 after adding Factory 

// import java.util.List;

// import lox;

// abstract class Expr_v2 {
//   static class Binary extends Expr_v2 {
//     Binary(Expr_v2 left, Token operator, Expr_v2 right) {
//       this.left = left;
//       this.operator = operator;
//       this.right = right;
//     }

//     final Expr_v2 left;
//     final Token operator;
//     final Expr_v2 right;
//   }
//   static class Grouping extends Expr_v2 {
//     Grouping(Expr_v2 expression) {
//       this.expression = expression;
//     }

//     final Expr_v2 expression;
//   }
//   static class Literal extends Expr_v2 {
//     Literal(Object value) {
//       this.value = value;
//     }

//     final Object value;
//   }
//   static class Unary extends Expr_v2 {
//     Unary(Token operator, Expr_v2 right) {
//       this.operator = operator;
//       this.right = right;
//     }

//     final Token operator;
//     final Expr_v2 right;
//   }
// }
